### ISSUE TITLE
pretrained checkpoints.

### ISSUE THREAD

**Issue by xiaochehe** [vita-epfl/openpifpaf_posetrack#3]
Hello, I want to use your code as a video-based skeleton extraction tool in my work. Could you provide the pretrained checkpoint?
Thanks!

**Comment by svenkreiss** [comment]
Hello @xiaochehe , have you tried `--checkpoint=tshufflenetv2k30`? 
That downloads the pretrained checkpoint and uses it.

**Comment by xiaochehe** [comment]
@svenkreiss I will try. Thank you so much!
