### ISSUE TITLE
How to crop Specific areas in video? And a more powerful pretrained model

### ISSUE THREAD

**Issue by xiaochehe** [vita-epfl/openpifpaf_posetrack#4]
Hello, I have read the document of openpifpaf. I understand that I can set the optional argument in openpifpaf.video to realize it.
So I added following cmd:
**python3 -m openpifpaf.video --crop 20 30 1200 700**
but, openpifpaf give me a error message: **unrecognized arguments:  20 30 1200 700**
How can i fix it?

Meanwhile, Is the tshufflenet2k16 the only pre-trained model? It's fast, but it's not as powerful as I expected. Can **a more powerful pretrained model** be provided?
Thanks

**Comment by svenkreiss** [comment]
That exact command works for me. Can you post the output of `python3 -m openpifpaf.video --version`? It should be at least a 0.12 version.

We will have a more powerful pre-trained model soon.

**Comment by xiaochehe** [comment]
> That exact command works for me. Can you post the output of `python3 -m openpifpaf.video --version`? It should be at least a 0.12 version.
> 
> We will have a more powerful pre-trained model soon.

It worked when I updated the version! Thanks
