### ISSUE TITLE
Is there any setting to imporve the tracking performance?

### ISSUE THREAD

**Issue by xiaochehe** [vita-epfl/openpifpaf_posetrack#5]
I have to say that the effect of pose estimation is excellent. However,  I found a problem that When a person is completely occluded, he will get a new ID when be detected again, no matter how long or how far he has moved.  Is there any way to alleviate this problem? 
'' python3 -m openpifpaf.video --show --long-edge=321 --checkpoint=tshufflenetv2k16 --decoder=trackingpose:0 --source 0 '' I used this cmd line.
![d5992883f1ebec4a072e1f5af9e8141](https://user-images.githubusercontent.com/16096446/112114003-7ec33180-8bf2-11eb-9d0c-dbc0b16bf2f4.png)
![74f66275bf0dd7a6352bd1cb1e239fe](https://user-images.githubusercontent.com/16096446/112114014-8387e580-8bf2-11eb-9a09-f2de391bf081.png)

**Comment by svenkreiss** [comment]
Nice examples @xiaochehe . I hadn't tried it on Volleyball.

At the moment, we don't have a solution for full occlusions.
